<?php
/**
 * Project Pillar â€” bep-an-truong-mam-non-tu-thuc-trinh-vuong
 * Section #2: with_gallery
 * @package SaigonHoreca
 */
if (!defined('ABSPATH')) exit;
$uri = get_template_directory_uri();
?>
<section class="pp-section-tvg pp-section-tvg--alt scroll-reveal">
  <div class="pp-container-shared">
    <div class="pp-text-tvg pp-text-tvg--center">
      <span class="pp-text-tvg__divider pp-text-tvg__divider--center" aria-hidden="true"></span>
      <h2 class="pp-text-tvg__title"><?php echo esc_html__('Bài toán đặt ra – Bếp học đường, nơi tốc độ và an toàn phải song hành', 'saigonhoreca'); ?></h2>
      <div class="pp-text-tvg__body">
      <p><?php echo esc_html__('Với đặc thù bếp học đường, nơi mỗi suất ăn là một "nhiệm vụ dinh dưỡng" dành cho trẻ nhỏ, yêu cầu về tốc độ, an toàn và vệ sinh thực phẩm (VSATTP) luôn được đặt lên hàng đầu. Một sai lệch nhỏ trong quy trình nấu – vận hành đều có thể ảnh hưởng đến hàng trăm phần ăn cùng lúc. Chính vì vậy, bếp công nghiệp cho trường học không chỉ cần thiết bị mạnh mẽ, mà quan trọng hơn là một quy hoạch khoa học – nơi từng khu vực, từng thao tác được sắp đặt để vận hành nhịp nhàng như một cỗ máy tinh chỉnh.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Trong dự án này, Saigon Horeca đã mang đến cho Trường Trinh Vương một hệ thống bếp hiện đại diện tích 150m², có khả năng phục vụ toàn bộ 500 suất ăn cùng lúc mà vẫn đảm bảo yếu tố ngon – sạch – đúng giờ. Đó là kết quả của việc kết hợp giữa hiểu biết chuyên sâu về bếp công nghiệp và tư duy thiết kế tối ưu trải nghiệm vận hành, điều đã làm nên dấu ấn của SGH trong hàng loạt dự án bếp học đường, bếp nhà hàng và cÄƒng-tin chuyên nghiệp.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Nếu như bếp nhà hàng có thể linh hoạt giờ phục vụ, bếp bệnh viện có thể chia theo từng khoa, thì bếp Äƒn trÆ°á»ng há»c láº¡i lÃ  nÆ¡i duy nháº¥t mÃ  hÃ ng trÄƒm suáº¥t Äƒn pháº£i Ä‘Æ°á»£c hoÃ n thÃ nh cÃ¹ng má»™t thá»i Ä‘iá»ƒm.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('á»ž TrÆ°á»ng Máº§m Non TÆ° Thá»¥c Trinh VÆ°Æ¡ng, gáº§n 500 bÃ© tá»« 3 Ä‘áº¿n 7 tuá»•i dÃ¹ng bá»¯a trÆ°a cÃ¹ng lÃºc. NghÄ©a lÃ  chá»‰ trong vÃ i chá»¥c phÃºt, toÃ n bá»™ quy trÃ¬nh tá»« náº¥u â€“ phÃ¢n khu chia â€“ giao mÃ³n pháº£i diá»…n ra hoÃ n toÃ n chÃ­nh xÃ¡c, khÃ´ng cháº­m trá»…, khÃ´ng sai sÃ³t.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('ÄÃ³ lÃ  má»™t thá»­ thÃ¡ch lá»›n vá» hiá»‡u suáº¥t, tá»• chá»©c khÃ´ng gian vÃ  thiáº¿t bá»‹. Bá»Ÿi chá»‰ cáº§n má»™t khÃ¢u váº­n hÃ nh bá»‹ ngháº½n â€“ cháº£o náº¥u quÃ¡ nhá», khu chia khÃ´ng Ä‘á»§ diá»‡n tÃ­ch, hay lá»‘i di chuyá»ƒn bá»‹ cáº¯t ngang â€“ sáº½ kÃ©o theo cáº£ dÃ¢y chuyá»n bá»‹ cháº­m láº¡i. Trong mÃ´i trÆ°á»ng há»c Ä‘Æ°á»ng, nÆ¡i giá» Äƒn cá»§a tráº» gáº¯n liá»n vá»›i Ä‘á»“ng há»“ sinh há»c vÃ  sá»©c khá»e tiÃªu hÃ³a, thÃ¬ "Ä‘Ãºng giá»" khÃ´ng chá»‰ lÃ  yÃªu cáº§u váº­n hÃ nh, mÃ  lÃ  tiÃªu chuáº©n chÄƒm sÃ³c.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('NgoÃ i yáº¿u tá»‘ tá»‘c Ä‘á»™, an toÃ n vá»‡ sinh thá»±c pháº©m (VSATTP) lÃ  Æ°u tiÃªn tuyá»‡t Ä‘á»‘i. Tá»« nguá»“n nguyÃªn liá»‡u tÆ°Æ¡i sá»‘ng, quÃ¡ trÃ¬nh sÆ¡ cháº¿, Ä‘áº¿n khu vá»±c náº¥u vÃ  chia mÃ³n â€“ táº¥t cáº£ pháº£i váº­n hÃ nh theo nguyÃªn táº¯c má»™t chiá»u, ngÄƒn chÃ©o nhiá»…m vÃ  báº£o Ä‘áº£m vá»‡ sinh tuyá»‡t Ä‘á»‘i. Má»i thiáº¿t bá»‹, bá» máº·t, Ä‘Æ°á»ng dáº«n khÃ­ â€“ nÆ°á»›c â€“ rÃ¡c Ä‘á»u cáº§n Ä‘Æ°á»£c thiáº¿t káº¿ Ä‘á»ƒ giáº£m tiáº¿p xÃºc, dá»… lÃ m sáº¡ch, dá»… kiá»ƒm soÃ¡t.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('ThÃªm vÃ o Ä‘Ã³, nhÃ¢n sá»± báº¿p cá»§a trÆ°á»ng há»c thÆ°á»ng khÃ´ng nhiá»u, nÃªn giáº£i phÃ¡p tá»‘i Æ°u khÃ´ng náº±m á»Ÿ viá»‡c tÄƒng ngÆ°á»i, mÃ  lÃ  tÄƒng nÄƒng suáº¥t váº­n hÃ nh thÃ´ng qua thiáº¿t bá»‹ phÃ¹ há»£p: cháº£o tay quay Ä‘iá»‡n Ä‘á»ƒ náº¥u lÆ°á»£ng lá»›n, tá»§ háº¥p cÃ´ng suáº¥t cao, bÃ n chia bá»‘ trÃ­ thuáº­n tay â€“ táº¥t cáº£ Ä‘á»u gÃ³p pháº§n tiáº¿t kiá»‡m thá»i gian vÃ  sá»©c lao Ä‘á»™ng, Ä‘á»“ng thá»i nÃ¢ng cao Ä‘á»™ chÃ­nh xÃ¡c khi phá»¥c vá»¥.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Vá»›i bÃ i toÃ¡n vá»«a Ä‘Ã²i há»i hiá»‡u suáº¥t cao, vá»«a yÃªu cáº§u chuáº©n VSATTP nghiÃªm ngáº·t, Saigon Horeca Ä‘Ã£ bÆ°á»›c vÃ o dá»± Ã¡n Trinh VÆ°Æ¡ng vá»›i tÆ° duy:', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('"Má»—i chi tiáº¿t trong báº¿p pháº£i lÃ m viá»‡c nhÆ° má»™t máº¯t xÃ­ch trong dÃ¢y chuyá»n â€“ nhá»‹p nhÃ ng, an toÃ n vÃ  hiá»‡u quáº£."', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Ngay tá»« khÃ¢u kháº£o sÃ¡t, Ä‘á»™i ngÅ© ká»¹ sÆ° Saigon Horeca Ä‘Ã£ nháº­n tháº¥y ráº±ng: Ä‘á»ƒ biáº¿n khÃ´ng gian 11mÂ² thÃ nh má»™t báº¿p bÃ¡nh kiÃªm bar cafÃ© hiá»‡u quáº£, khÃ´ng thá»ƒ dÃ¹ng thiáº¿t bá»‹ tiÃªu chuáº©n sáºµn cÃ³, mÃ  pháº£i custom toÃ n bá»™ thiáº¿t bá»‹ inox theo kÃ­ch thÆ°á»›c thá»±c táº¿.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Tá»«ng centimet Ä‘Æ°á»£c tÃ­nh toÃ¡n ká»¹ lÆ°á»¡ng:', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Khu rá»­a & lÆ°u trá»¯ dá»¥ng cá»¥: mÃ¡y rá»­a chÃ©n vÃ  ká»‡ inox 3 táº§ng giÃºp tá»‘i Æ°u khÃ´ng gian tháº³ng Ä‘á»©ng, háº¡n cháº¿ bá» máº·t tiáº¿p xÃºc â€“ dá»… vá»‡ sinh, sáº¡ch sáº½ tuyá»‡t Ä‘á»‘i.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Äá»‘i vá»›i Saigon Horeca, thiáº¿t káº¿ báº¿p cÃ´ng nghiá»‡p khÃ´ng chá»‰ lÃ  sáº¯p xáº¿p thiáº¿t bá»‹ cho "Ä‘á»§ chá»—", mÃ  lÃ  xÃ¢y dá»±ng má»™t há»‡ thá»‘ng váº­n hÃ nh cÃ³ logic, cÃ³ nhá»‹p Ä‘iá»‡u vÃ  cÃ³ táº§m nhÃ¬n dÃ i háº¡n.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Vá»›i báº¿p TrÆ°á»ng Máº§m Non Trinh VÆ°Æ¡ng, bÃ i toÃ¡n Ä‘Æ°á»£c SGH giáº£i quyáº¿t dá»±a trÃªn hai nguyÃªn táº¯c cá»‘t lÃµi: hiá»‡u suáº¥t váº­n hÃ nh tá»‘i Ä‘a vÃ  Ä‘áº£m báº£o an toÃ n â€“ vá»‡ sinh tuyá»‡t Ä‘á»‘i trong toÃ n bá»™ quy trÃ¬nh náº¥u Äƒn.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Quy hoáº¡ch tá»•ng thá»ƒ â€“ luá»“ng váº­n hÃ nh má»™t chiá»u khÃ©p kÃ­n', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Dá»±a trÃªn layout tá»•ng thá»ƒ, SGH Ä‘Ã£ bá»‘ trÃ­ 150mÂ² khÃ´ng gian báº¿p thÃ nh cÃ¡c khu vá»±c cÃ´ng nÄƒng tÃ¡ch biá»‡t, váº­n hÃ nh theo nguyÃªn táº¯c má»™t chiá»u â€“ tá»« nháº­p hÃ ng â†’ sÆ¡ cháº¿ â†’ náº¥u â†’ chia â†’ rá»­a.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('CÃ¡ch phÃ¢n luá»“ng khoa há»c nÃ y giÃºp háº¡n cháº¿ tá»‘i Ä‘a viá»‡c giao chÃ©o giá»¯a nguyÃªn liá»‡u sá»‘ng vÃ  thá»±c pháº©m chÃ­n â€“ yáº¿u tá»‘ quan trá»ng hÃ ng Ä‘áº§u trong báº¿p há»c Ä‘Æ°á»ng.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Thiáº¿t bá»‹ chá»§ lá»±c â€“ cÃ´ng suáº¥t lá»›n, dá»… váº­n hÃ nh, tiáº¿t kiá»‡m nhÃ¢n sá»±', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Äá»ƒ Ä‘Ã¡p á»©ng nhu cáº§u phá»¥c vá»¥ 500 suáº¥t Äƒn cÃ¹ng lÃºc, SGH Ä‘Ã£ lá»±a chá»n vÃ  láº¯p Ä‘áº·t há»‡ thá»‘ng thiáº¿t bá»‹ phÃ¹ há»£p cáº£ vá» dung tÃ­ch vÃ  hiá»‡u suáº¥t:', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Táº¥t cáº£ thiáº¿t bá»‹ Ä‘á»u Ä‘Æ°á»£c SGH lá»±a chá»n tá»« thÆ°Æ¡ng hiá»‡u uy tÃ­n, Ä‘áº¡t chuáº©n an toÃ n Ä‘iá»‡n â€“ gas, vÃ  dá»… dÃ ng báº£o trÃ¬ sau bÃ n giao.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Tá»‘i Æ°u tiá»‡n nghi vÃ  an toÃ n trong váº­n hÃ nh', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('BÃªn cáº¡nh cÃ´ng suáº¥t, SGH chÃº trá»ng Ä‘áº¿n an toÃ n lao Ä‘á»™ng vÃ  mÃ´i trÆ°á»ng báº¿p:', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Má»—i chi tiáº¿t nhá» â€“ tá»« Ä‘á»™ cao bÃ n, vá»‹ trÃ­ á»• Ä‘iá»‡n, cho Ä‘áº¿n hÆ°á»›ng má»Ÿ cá»­a tá»§ â€“ Ä‘á»u Ä‘Æ°á»£c tÃ­nh toÃ¡n dá»±a trÃªn thá»±c táº¿ váº­n hÃ nh cá»§a nhÃ¢n sá»± báº¿p há»c Ä‘Æ°á»ng, chá»© khÃ´ng Ä‘Æ¡n thuáº§n lÃ  báº£n váº½ ká»¹ thuáº­t.', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Káº¿t ná»‘i triáº¿t lÃ½ thiáº¿t káº¿ vá»›i hiá»‡u quáº£ thá»±c táº¿', 'saigonhoreca'); ?></p>
      <p><?php echo esc_html__('Saigon Horeca khÃ´ng thiáº¿t káº¿ Ä‘á»ƒ "Ä‘áº¹p trÃªn báº£n váº½", mÃ  Ä‘á»ƒ báº¿p váº­n hÃ nh tá»‘t ngoÃ i Ä‘á»i tháº­t. VÃ  táº¡i TrÆ°á»ng Máº§m Non Trinh VÆ°Æ¡ng, káº¿t quáº£ Ä‘Æ°á»£c thá»ƒ hiá»‡n rÃµ: 500 suáº¥t Äƒn Ä‘Æ°á»£c chuáº©n bá»‹ Ä‘áº§y Ä‘á»§, nÃ³ng há»•i, Ä‘Ãºng giá» â€“ má»—i ngÃ y. ÄÃ³ chÃ­nh lÃ  giÃ¡ trá»‹ mÃ  SGH luÃ´n theo Ä‘uá»•i trong má»i dá»± Ã¡n: "Hiá»‡u quáº£ báº¯t Ä‘áº§u tá»« chi tiáº¿t â€“ vÃ  chi tiáº¿t báº¯t Ä‘áº§u tá»« sá»± tháº¥u hiá»ƒu."', 'saigonhoreca'); ?></p>
      </div>
    </div>
    <div class="pp-gallery-tvg pp-gallery-tvg--cols-4" style="margin-top:2rem;">
      <div class="pp-gallery-tvg__item pp-image-container-shared"><img src="<?php echo sgh_img('2025/11/du-an-truong-mn-trinh-vuong-1.jpg'); ?>" alt="du-an-truong-mn-trinh-vuong (1)" loading="lazy" decoding="async"><div class="pp-image-caption-shared"><?php echo esc_html__('Hệ thống bếp 150m² phục vụ 500 suất ăn/ngày', 'saigonhoreca'); ?></div></div>
      <div class="pp-gallery-tvg__item pp-image-container-shared"><img src="<?php echo sgh_img('2025/11/du-an-truong-mn-trinh-vuong.jpg'); ?>" alt="du-an-truong-mn-trinh-vuong" loading="lazy" decoding="async"><div class="pp-image-caption-shared"><?php echo esc_html__('Luồng vận hành một chiều khép kín', 'saigonhoreca'); ?></div></div>
      <div class="pp-gallery-tvg__item pp-image-container-shared"><img src="<?php echo sgh_img('2025/11/du-an-truong-mn-trinh-vuong-3.jpg'); ?>" alt="du-an-truong-mn-trinh-vuong (3)" loading="lazy" decoding="async"><div class="pp-image-caption-shared"><?php echo esc_html__('Chảo tay quay điện nấu lượng lớn', 'saigonhoreca'); ?></div></div>
      <div class="pp-gallery-tvg__item pp-image-container-shared"><img src="<?php echo sgh_img('2025/11/du-an-truong-mn-trinh-vuong-2.jpg'); ?>" alt="du-an-truong-mn-trinh-vuong (2)" loading="lazy" decoding="async"><div class="pp-image-caption-shared"><?php echo esc_html__('Tủ hấp công suất cao tiết kiệm nhân sự', 'saigonhoreca'); ?></div></div>
      <div class="pp-gallery-tvg__item pp-image-container-shared"><img src="<?php echo sgh_img('2025/11/du-an-truong-mn-trinh-vuong-4.jpg'); ?>" alt="<?php echo esc_attr__('Thiáº¿t bá»‹ báº¿p cÃ´ng nghiá»‡p Saigon Horeca', 'saigonhoreca'); ?>" loading="lazy" decoding="async" width="1366" height="768"><div class="pp-image-caption-shared"><?php echo esc_html__('Thiết bị đạt chuẩn an toàn điện – gas', 'saigonhoreca'); ?></div></div>
      <div class="pp-gallery-tvg__item pp-image-container-shared"><img src="<?php echo sgh_img('2025/11/du-an-truong-mn-trinh-vuong-6.jpg'); ?>" alt="<?php echo esc_attr__('Thiáº¿t bá»‹ báº¿p cÃ´ng nghiá»‡p Saigon Horeca', 'saigonhoreca'); ?>" loading="lazy" decoding="async" width="1366" height="768"><div class="pp-image-caption-shared"><?php echo esc_html__('An toàn lao động và môi trường bếp học đường', 'saigonhoreca'); ?></div></div>
    </div>
  </div>
</section>

