#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────
# update-agent-metrics.sh — Compute per-agent metrics from LEADERBOARD
# ──────────────────────────────────────────────────────────────────
# Adopted from Overstory's persistent agent CV pattern.
# Reads LEADERBOARD.md → computes per-agent stats → writes to:
#   - AGENTS/<name>.md frontmatter (metrics_updated, total_tasks, pass_rate, last_active)
#   - AGENTS/<name>.md "## Performance Metrics" block (auto-generated, idempotent)
#
# Usage:
#   bash system/scripts/update-agent-metrics.sh
# ──────────────────────────────────────────────────────────────────

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HANDOFFS_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

winpath() { command -v cygpath >/dev/null 2>&1 && cygpath -m "$1" || echo "$1"; }

export LB_PATH="$(winpath "$HANDOFFS_DIR/LEADERBOARD.md")"
export AGENTS_DIR="$(winpath "$HANDOFFS_DIR/AGENTS")"
export ROSTER_PATH="$(winpath "$HANDOFFS_DIR/system/__roster.json")"

python <<'PYEOF'
import json, re, os, sys
from collections import defaultdict
from datetime import date

lb_path     = os.environ['LB_PATH']
agents_dir  = os.environ['AGENTS_DIR']
roster_path = os.environ['ROSTER_PATH']

roster = json.load(open(roster_path, encoding='utf-8'))
agent_names = set(roster['agents'].keys())
alias_to_canonical = {}
for name, meta in roster['agents'].items():
    alias_to_canonical[name] = name
    for a in meta.get('aliases', []):
        alias_to_canonical[a.lower()] = name

stats = defaultdict(lambda: {
    'total': 0, 'pass': 0, 'pass_warn': 0, 'fail': 0, 'reverted': 0,
    'last_active': None, 'types': defaultdict(int),
})

lb_text = open(lb_path, encoding='utf-8').read()
in_code = False
for line in lb_text.splitlines():
    s = line.strip()
    if s in ('```text', '```'):
        in_code = not in_code
        continue
    if not in_code:
        continue
    parts = [p.strip() for p in line.split('|')]
    if len(parts) < 5:
        continue
    if not re.match(r'^\d{4}-\d{2}-\d{2}$', parts[0]):
        continue
    d, _tid, agent_raw, ttype, result = parts[0], parts[1], parts[2].lower(), parts[3], parts[4]
    agent = alias_to_canonical.get(agent_raw, agent_raw)
    if agent not in agent_names:
        continue
    st = stats[agent]
    st['total'] += 1
    if result == 'pass':        st['pass'] += 1
    elif result == 'pass-warn': st['pass_warn'] += 1
    elif result == 'reverted':  st['reverted'] += 1
    else:                        st['fail'] += 1
    st['types'][ttype] += 1
    if st['last_active'] is None or d > st['last_active']:
        st['last_active'] = d

today = date.today().isoformat()
updated = 0

for name in agent_names:
    p = os.path.join(agents_dir, name + '.md')
    if not os.path.exists(p):
        alt = os.path.join(agents_dir, name.capitalize() + '.md')
        if os.path.exists(alt):
            p = alt
        else:
            continue
    st = stats[name]
    pass_rate = round(100 * (st['pass'] + st['pass_warn']) / st['total'], 1) if st['total'] else 0.0
    top3 = sorted(st['types'].items(), key=lambda x: -x[1])[:3]
    top3_str = ', '.join('{}({})'.format(t, n) for t, n in top3) if top3 else '—'
    last_active = st['last_active'] or 'never'

    content = open(p, encoding='utf-8').read()

    if content.startswith('---'):
        fm_end = content.find('\n---', 4)
        if fm_end > 0:
            fm = content[4:fm_end]
            body = content[fm_end+4:]
            fm_lines = [l for l in fm.splitlines() if not l.startswith(('metrics_updated:', 'total_tasks:', 'pass_rate:', 'last_active:'))]
            fm_lines.append('metrics_updated: ' + today)
            fm_lines.append('total_tasks: ' + str(st['total']))
            fm_lines.append('pass_rate: ' + str(pass_rate))
            fm_lines.append('last_active: ' + last_active)
            content = '---\n' + '\n'.join(fm_lines).rstrip() + '\n---' + body

    metrics_block = (
        '<!-- metrics:auto -->\n'
        '## 📊 Performance Metrics\n\n'
        '> Auto-generated by `system/scripts/update-agent-metrics.sh` from `LEADERBOARD.md`. Do not edit by hand.\n\n'
        '- **Total tasks**: ' + str(st['total']) + '\n'
        '- **Pass rate**: ' + str(pass_rate) + '% '
        '(' + str(st['pass']) + ' pass, ' + str(st['pass_warn']) + ' pass-warn, '
            + str(st['reverted']) + ' reverted, ' + str(st['fail']) + ' fail)\n'
        '- **Last active**: ' + last_active + '\n'
        '- **Top task types**: ' + top3_str + '\n'
        '- **Last refreshed**: ' + today + '\n'
        '<!-- /metrics:auto -->'
    )

    if '<!-- metrics:auto -->' in content:
        content = re.sub(r'<!-- metrics:auto -->.*?<!-- /metrics:auto -->', metrics_block, content, flags=re.DOTALL)
    else:
        content = content.rstrip() + '\n\n' + metrics_block + '\n'

    open(p, 'w', encoding='utf-8').write(content)
    updated += 1

print('Updated ' + str(updated) + ' agent CV(s) from LEADERBOARD')
PYEOF
