<?php
/**
 * Auto Setup — Saigon Horeca
 *
 * Saigonhouse-theme's auto-setup created a "Trang Chủ" page and forced
 * `show_on_front=page` + `page_on_front=<id>` so the WP-native front-page
 * template would render. Saigonhoreca's homepage is served by the
 * static-mirror handler (inc/core/static-mirror.php) which produces a
 * pixel-perfect saigonhoreca.vn replica — forcing the WP-native render
 * path would short-circuit that and emit unstyled Elementor markup.
 *
 * Net result: this file is intentionally a no-op until we rebuild the
 * homepage in pure Tailwind v4 utilities and can drop the mirror dependency
 * for `/`.
 *
 * @package SaigonHoreca
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * No-op stub kept under the saigonhouse_ prefix because other modules
 * (admin notices, dashboard menu, etc.) check `function_exists(...)` to
 * decide whether to surface the front-page setup CTA in wp-admin.
 *
 * If/when the homepage is rebuilt natively, restore the original logic
 * (see saigonhoreca-theme/inc/core/auto-setup.php for the original
 * implementation).
 */
if (!function_exists('saigonhouse_auto_setup_front_page')) {
    function saigonhouse_auto_setup_front_page() {
        // Intentional no-op — mirror handler serves the front page.
    }
}

// Tự động deploy .htaccess, robots.txt, và OG image khi kích hoạt theme (add/switch theme)
add_action('after_switch_theme', function() {
    $deploy_file = get_template_directory() . '/inc/admin/sync/sync-deploy.php';
    if (file_exists($deploy_file)) {
        require_once $deploy_file;
    }

    if (function_exists('sgh_dashboard_deploy_htaccess')) {
        sgh_dashboard_deploy_htaccess();
    }
    if (function_exists('sgh_dashboard_deploy_robots_txt')) {
        sgh_dashboard_deploy_robots_txt();
    }
    if (function_exists('sgh_dashboard_deploy_og_image')) {
        sgh_dashboard_deploy_og_image();
    }

    // Auto-create the WP nav menu on theme activation if dashboard sync is wired.
    if (function_exists('sgh_dashboard_sync_menu')) {
        sgh_dashboard_sync_menu();
    }
});

// Self-healing: Tự động kiểm tra, khôi phục hoặc nâng cấp các file cấu hình hệ thống (.htaccess, robots.txt, og-default.png) ở WordPress root
add_action('wp_loaded', function() {
    $wp_root = ABSPATH;
    $htaccess_path = $wp_root . '.htaccess';
    $robots_path   = $wp_root . 'robots.txt';
    $og_image_path = $wp_root . 'og-default.png';

    $need_htaccess = !file_exists($htaccess_path);
    if (!$need_htaccess) {
        // Nếu .htaccess đã tồn tại, kiểm tra xem đã có cấu hình tối ưu của theme (SGH_STATIC_CACHE) chưa
        $htaccess_content = @file_get_contents($htaccess_path);
        if ($htaccess_content !== false && strpos($htaccess_content, 'SGH_STATIC_CACHE') === false) {
            $need_htaccess = true; // Cần đè/nâng cấp lên bản premium của theme
        }
    }

    $need_robots = !file_exists($robots_path);
    if (!$need_robots) {
        // Nếu robots.txt đã tồn tại, kiểm tra xem đã có cấu hình chuẩn SEO của theme chưa
        $robots_content = @file_get_contents($robots_path);
        if ($robots_content !== false && strpos($robots_content, 'Generated by Saigon Horeca Theme') === false) {
            $need_robots = true; // Cần đè/nâng cấp bản tối ưu mới nhất
        }
    }

    $need_og_image = !file_exists($og_image_path);

    if ($need_htaccess || $need_robots || $need_og_image) {
        $deploy_file = get_template_directory() . '/inc/admin/sync/sync-deploy.php';
        if (file_exists($deploy_file)) {
            require_once $deploy_file;
        }

        // Tự động deploy / khôi phục các file cấu hình tương ứng
        if ($need_htaccess && function_exists('sgh_dashboard_deploy_htaccess')) {
            sgh_dashboard_deploy_htaccess();
        }
        if ($need_robots && function_exists('sgh_dashboard_deploy_robots_txt')) {
            sgh_dashboard_deploy_robots_txt();
        }
        if ($need_og_image && function_exists('sgh_dashboard_deploy_og_image')) {
            sgh_dashboard_deploy_og_image();
        }
    }

    // Auto-sync theme file templates' "* Thumbnail:" values directly into WP database (_thumbnail_id)
    if (is_admin() || !wp_doing_ajax()) {
        try {
            $projects = get_posts([
                'post_type'      => 'project',
                'post_status'    => 'any',
                'posts_per_page' => -1,
                'no_found_rows'  => true,
            ]);
            
            if (!empty($projects)) {
                foreach ($projects as $proj) {
                    $slug = $proj->post_name;
                    if (empty($slug)) continue;

                    if (function_exists('sgh_get_project_thumbnail')) {
                        $custom_thumb = sgh_get_project_thumbnail($slug);
                        if (!empty($custom_thumb)) {
                            // We have a custom template thumbnail defined. 
                            // Check if _thumbnail_id is set or matches this media attachment.
                            $existing_thumb_id = get_post_thumbnail_id($proj->ID);
                            
                            // Parse relative file path from thumbnail URL
                            $uploads_url = function_exists('sgh_uploads_base_url') ? sgh_uploads_base_url() : wp_get_upload_dir()['baseurl'];
                            $rel_path = str_replace($uploads_url . '/', '', $custom_thumb);
                            
                            if (empty($existing_thumb_id)) {
                                // Find or insert the attachment in the DB
                                $attach_id = attachment_url_to_postid($custom_thumb);
                                if (!$attach_id) {
                                    $uploads_dir = function_exists('sgh_uploads_base_dir') ? sgh_uploads_base_dir() : wp_get_upload_dir()['basedir'];
                                    $file_path = wp_normalize_path($uploads_dir . '/' . $rel_path);
                                    
                                    if (file_exists($file_path)) {
                                        $wp_filetype = wp_check_filetype($file_path, null);
                                        $attachment = [
                                            'post_mime_type' => $wp_filetype['type'],
                                            'post_title'     => sanitize_file_name(basename($file_path)),
                                            'post_content'   => '',
                                            'post_status'    => 'inherit'
                                        ];
                                        $attach_id = wp_insert_attachment($attachment, $file_path, $proj->ID);
                                        if (!is_wp_error($attach_id) && $attach_id > 0) {
                                            require_once ABSPATH . 'wp-admin/includes/image.php';
                                            $attach_data = wp_generate_attachment_metadata($attach_id, $file_path);
                                            wp_update_attachment_metadata($attach_id, $attach_data);
                                        }
                                    }
                                }
                                
                                if ($attach_id && !is_wp_error($attach_id)) {
                                    set_post_thumbnail($proj->ID, $attach_id);
                                }
                            }
                        }
                    }
                }
            }
        } catch (\Throwable $ex) {
            // Safe fallback to prevent active process crash
        }
    }
});

/**
 * Auto-inject AUTOMATIC_UPDATER_DISABLED into wp-config.php to prevent WP
 * update warnings on servers without wordpress.org access. Runs once on
 * theme activation. (Preserved from saigonhoreca-theme.)
 */
add_action('after_switch_theme', 'saigonhouse_inject_wp_config_constants');
add_action('admin_init', function() {
    if (!get_option('sgh_wpconfig_patched')) {
        if (function_exists('saigonhouse_inject_wp_config_constants')) {
            saigonhouse_inject_wp_config_constants();
        }
        update_option('sgh_wpconfig_patched', 1);
    }
});

if (!function_exists('saigonhouse_inject_wp_config_constants')) {
    function saigonhouse_inject_wp_config_constants() {
        // No-op stub — production patching of wp-config.php is out of scope
        // for the saigonhoreca local environment.
    }
}

/**
 * ─────────────────────────────────────────────────────────────────────
 * VIETNAMESE UNICODE NORMALIZER (NFC COMPOSER)
 *
 * Tự động kiểm tra và chuẩn hóa mọi chuỗi tiếng Việt từ dạng tổ hợp (NFD)
 * sang dạng dựng sẵn (NFC). Giải quyết triệt để lỗi font chữ bị rách dấu,
 * rải rác dấu (ví dụ să ́p → sắp) trên toàn trang WordPress.
 * ─────────────────────────────────────────────────────────────────────
 */
if (!function_exists('sgh_normalize_vietnamese_nfc')) {
    function sgh_normalize_vietnamese_nfc($text) {
        if (empty($text) || !is_string($text)) {
            return $text;
        }

        // Chỉ xử lý nếu class Normalizer (intl extension) tồn tại
        if (class_exists('Normalizer')) {
            if (Normalizer::isNormalized($text, Normalizer::FORM_C) === false) {
                return Normalizer::normalize($text, Normalizer::FORM_C);
            }
        }

        return $text;
    }
}

// Hook vào gettext lọc dịch PO/MO lỗi dấu tổ hợp từ server production crawl về
add_filter('gettext', 'sgh_normalize_vietnamese_nfc', 9999);
add_filter('gettext_with_context', 'sgh_normalize_vietnamese_nfc', 9999);

// Hook vào các filter nội dung chính để chuẩn hóa dữ liệu đầu ra từ database hoặc file PHP
add_filter('the_content', 'sgh_normalize_vietnamese_nfc', 9999);
add_filter('the_title', 'sgh_normalize_vietnamese_nfc', 9999);
add_filter('the_excerpt', 'sgh_normalize_vietnamese_nfc', 9999);
add_filter('widget_text', 'sgh_normalize_vietnamese_nfc', 9999);
add_filter('widget_title', 'sgh_normalize_vietnamese_nfc', 9999);

/**
 * Tự động gỡ bỏ các hàm dịch gettext lỗi tiếng Việt trong thư mục project-pillar/amdang-typhoon
 * và thay thế bằng in trực tiếp chuẩn NFC, tránh đè bản dịch lỗi NFD từ file .mo/.po.
 * Trigger bằng cách truy cập: https://saigonhoreca.local/du-an/amdang-typhoon/?sgh_strip_gettext=1
 */
add_action('wp_loaded', function() {
    if (isset($_GET['sgh_strip_gettext'])) {
        $dir = get_template_directory() . '/template-parts/project-pillar/amdang-typhoon';
        if (is_dir($dir)) {
            $files = glob($dir . '/*.php');
            $count = 0;
            foreach ($files as $file) {
                $content = @file_get_contents($file);
                if ($content !== false) {
                    // 1. Thay thế esc_html__('text', 'saigonhoreca') bằng esc_html('text')
                    $pattern_html = "/esc_html__\(\s*'((?:[^'\\\\]|\\\\.)*)'\s*,\s*'saigonhoreca'\s*\)/u";
                    $content = preg_replace($pattern_html, "esc_html('$1')", $content);

                    // 2. Thay thế esc_attr__('text', 'saigonhoreca') bằng esc_attr('text')
                    $pattern_attr = "/esc_attr__\(\s*'((?:[^'\\\\]|\\\\.)*)'\s*,\s*'saigonhoreca'\s*\)/u";
                    $content = preg_replace($pattern_attr, "esc_attr('$1')", $content);

                    // 3. Thay thế __('text', 'saigonhoreca') bằng esc_html('text')
                    $pattern_double = "/__\(\s*'((?:[^'\\\\]|\\\\.)*)'\s*,\s*'saigonhoreca'\s*\)/u";
                    $content = preg_replace($pattern_double, "esc_html('$1')", $content);

                    @file_put_contents($file, $content);
                    $count++;
                }
            }
            wp_die('Gettext strip completed. Cleaned ' . $count . ' files.');
        }
        wp_die('Amdang Typhoon directory not found.');
    }
});



